export interface MenuItem {
  id: number
  name: string
  category: string
  price: number
  priceLabel: string
  currency: 'INR'
  description: string
  image: string
  rating: number
  reviews: number
  badge?: string
  veg: boolean
  spicy?: boolean
}

export const CATEGORIES = [
  'All',
  'Soup',
  'Salad',
  'Fried Special',
  'Rice',
  'Sandwiches & Burgers',
  'Combo',
  'Mediterranean Mix Grill',
  'Beef Platter',
  'Lamb Platter',
  'Chicken Platter',
  'Grill Fish & Seafood',
  'Refreshers',
  'Shakes',
  'Smoothies',
  'Mojitos',
  'Wraps',
  'Signature',
  'Breakfast',
  'Breakfast Add-ons',
  'Non-Veg Snacks',
  'Veg Snacks',
] as const

export const ALL_MENU_ITEMS: MenuItem[] = [
  // --- SOUP ---
  {
    id: 1,
    name: 'Thai Soup (Shrimp / Chicken)',
    category: 'Soup',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Aromatic Thai Tom Yum soup infused with lemongrass, galangal, kaffir lime leaves, and your choice of tender shrimp or chicken.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 84,
    badge: 'Bestseller',
    veg: false,
    spicy: true,
  },
  {
    id: 2,
    name: 'Salmon Soup',
    category: 'Soup',
    price: 945,
    priceLabel: '₹945',
    currency: 'INR',
    description: 'Rich and velvety Nordic-style salmon soup made with fresh Atlantic salmon fillet, tender potatoes, and fresh dill in light cream broth.',
    image: 'https://images.unsplash.com/photo-1594756202469-9ff9799b2e4e?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 62,
    badge: 'Chef Special',
    veg: false,
  },
  {
    id: 3,
    name: 'Veggie Soup',
    category: 'Soup',
    price: 601,
    priceLabel: '₹601',
    currency: 'INR',
    description: 'Nourishing garden vegetable broth loaded with carrots, sweet corn, broccoli, zucchini, and aromatic garden herbs.',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85',
    rating: 4.7,
    reviews: 45,
    veg: true,
  },

  // --- SALAD ---
  {
    id: 4,
    name: 'Chicken Salad',
    category: 'Salad',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Char-grilled chicken breast served over a bed of crisp romaine, cherry tomatoes, cucumbers, and light garlic-herb dressing.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 78,
    veg: false,
  },
  {
    id: 5,
    name: 'Cashew Nut Salad with Chicken',
    category: 'Salad',
    price: 1031,
    priceLabel: '₹1031',
    currency: 'INR',
    description: 'Tender pulled chicken tossed with roasted cashews, bell peppers, scallions, and sweet sesame chili vinaigrette.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 92,
    badge: 'Must Try',
    veg: false,
  },
  {
    id: 6,
    name: 'Greek Salad',
    category: 'Salad',
    price: 945,
    priceLabel: '₹945',
    currency: 'INR',
    description: 'Authentic Mediterranean salad with rich feta cheese blocks, Kalamata olives, ripe tomatoes, red onion, and extra virgin olive oil.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=85',
    rating: 4.6,
    reviews: 51,
    veg: true,
  },

  // --- FRIED SPECIAL ---
  {
    id: 7,
    name: 'Hot Wings (6 pieces)',
    category: 'Fried Special',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Crispy fried jumbo chicken wings tossed in our signature fiery hot sauce served with cool buttermilk dip.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 135,
    badge: 'Popular',
    veg: false,
    spicy: true,
  },
  {
    id: 8,
    name: 'Peri Peri Wings (6 pieces)',
    category: 'Fried Special',
    price: 1031,
    priceLabel: '₹1031',
    currency: 'INR',
    description: 'Six jumbo wings coated in fiery African bird-eye chili marinade, flame-grilled and finished with lemon zests.',
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 110,
    badge: 'Chef Special',
    veg: false,
    spicy: true,
  },
  {
    id: 9,
    name: 'Buffalo Wings (6 pieces)',
    category: 'Fried Special',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Classic American style buffalo wings glazed in buttery cayenne pepper sauce with crisp celery sticks.',
    image: 'https://images.unsplash.com/photo-1734987942068-a1a459d65d3d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1lfHx8fGVufDB8fHx8fA%3D%3D',
    rating: 4.7,
    reviews: 89,
    veg: false,
    spicy: true,
  },
  {
    id: 10,
    name: 'Chicken Tenders (3 pieces with fries)',
    category: 'Fried Special',
    price: 601,
    priceLabel: '₹601',
    currency: 'INR',
    description: 'Golden buttermilk fried chicken breast tenders served alongside seasoned house cut fries and honey mustard dip.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 74,
    veg: false,
  },
  {
    id: 11,
    name: 'Jumbo Shrimp',
    category: 'Fried Special',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Succulent ocean jumbo shrimp coated in crispy breadcrumbs, served golden brown with house tartare sauce.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 67,
    badge: 'Must Try',
    veg: false,
  },
  {
    id: 12,
    name: 'Shrimp Tempura (6 pcs)',
    category: 'Fried Special',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Japanese style light and airy crispy tempura shrimp served with warm dashi dipping sauce.',
    image: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 58,
    veg: false,
  },
  {
    id: 13,
    name: 'Fish and Chips',
    category: 'Fried Special',
    price: 602,
    priceLabel: '₹602',
    currency: 'INR',
    description: 'Traditional beer-battered cod fillet fried to golden perfection, served with thick cut chips and tartar sauce.',
    image: 'https://images.unsplash.com/photo-1579208030886-b937da0925dc?auto=format&fit=crop&w=900&q=85',
    rating: 4.7,
    reviews: 95,
    veg: false,
  },

  // --- RICE ---
  {
    id: 14,
    name: 'Kabuli Pulao',
    category: 'Rice',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Royal Afghan basmati rice cooked with tender braised lamb shank, caramelized carrots, plump raisins, and toasted almonds.',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 142,
    badge: 'Signature',
    veg: false,
  },
  {
    id: 15,
    name: 'Chicken Fried Rice',
    category: 'Rice',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Wok-tossed aromatic long-grain jasmine rice with diced chicken breast, eggs, spring onions, and light soy sauce.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 116,
    veg: false,
  },
  {
    id: 16,
    name: 'Shrimp Fried Rice',
    category: 'Rice',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Fragrant wok-fried rice loaded with juicy pink shrimp, scrambled eggs, sweet peas, and savory oyster sauce.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 88,
    veg: false,
  },
  {
    id: 17,
    name: 'Mix Fried Rice',
    category: 'Rice',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'The ultimate wok special featuring chicken, shrimp, tender beef, mixed vegetables, and master broth seasoned rice.',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 104,
    badge: 'Bestseller',
    veg: false,
  },

  // --- SANDWICHES & BURGERS ---
  {
    id: 18,
    name: 'Chicken Shawarma',
    category: 'Sandwiches & Burgers',
    price: 773,
    priceLabel: '₹773',
    currency: 'INR',
    description: 'Slow-roasted marinated chicken shaved hot from the spit, wrapped in warm pita with toum garlic whip and dill pickles.',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 160,
    badge: 'Popular',
    veg: false,
  },
  {
    id: 19,
    name: 'Lamb Shawarma',
    category: 'Sandwiches & Burgers',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Tender spiced lamb shawarma shreds wrapped with roasted tomatoes, red onions, parsley, and creamy tahini sauce.',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 128,
    badge: 'Chef Special',
    veg: false,
  },
  {
    id: 20,
    name: 'Mix Shawarma',
    category: 'Sandwiches & Burgers',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Dual layer of flame-roasted chicken and lamb shawarma packed into warm lavash bread with signature house sauce.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 95,
    veg: false,
  },
  {
    id: 21,
    name: 'Chicken Kebab / Kofta Wrap',
    category: 'Sandwiches & Burgers',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Charcoal-grilled minced chicken kofta skewer rolled in flatbread with crisp lettuce, sumac onions, and garlic sauce.',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 72,
    veg: false,
  },
  {
    id: 22,
    name: 'Beef Kebab / Kofta Wrap',
    category: 'Sandwiches & Burgers',
    price: 1031,
    priceLabel: '₹1031',
    currency: 'INR',
    description: 'Juicy spiced beef kofta skewer grilled over charcoal, wrapped with fresh herb salad, pickles, and sesame tahini.',
    image: 'https://images.unsplash.com/photo-1771285119318-b342c3ecc51c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1lfHx8fGVufDB8fHx8fA%3D%3D',
    rating: 4.9,
    reviews: 84,
    veg: false,
  },
  {
    id: 23,
    name: 'Philly Cheese Steak',
    category: 'Sandwiches & Burgers',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Thinly sliced ribeye steak sautéed with caramelized onions and bell peppers, topped with melted provolone cheese on a toasted hoagie.',
    image: 'https://images.unsplash.com/photo-1521305916504-4a1121188589?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 112,
    badge: 'Bestseller',
    veg: false,
  },
  {
    id: 24,
    name: 'Falafel Sandwich',
    category: 'Sandwiches & Burgers',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: 'Crispy herb falafel patties stuffed in warm pita bread with diced cucumber, ripe tomato, turnip pickles, and tahini sauce.',
    image: '/images/avocado-sandwich.webp',
    rating: 4.7,
    reviews: 65,
    veg: true,
  },
  {
    id: 25,
    name: 'Chopped Salmon Sandwich',
    category: 'Sandwiches & Burgers',
    price: 1203,
    priceLabel: '₹1203',
    currency: 'INR',
    description: 'Flame-grilled salmon chopped with dill, capers, red onion, and dill-lemon cream sauce served on toasted brioche.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 49,
    badge: 'Chef Special',
    veg: false,
  },

  // --- COMBO ---
  {
    id: 26,
    name: 'Chicken Burger / Home Style',
    category: 'Combo',
    price: 773,
    priceLabel: '₹773',
    currency: 'INR',
    description: 'Juicy home-style ground chicken patty with aged cheddar, crisp lettuce, ripe tomato, and secret midway burger sauce.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 130,
    badge: 'Popular',
    veg: false,
  },
  {
    id: 27,
    name: 'Beef Burger / Home Style',
    category: 'Combo',
    price: 859,
    priceLabel: '₹859',
    currency: 'INR',
    description: '100% Angus beef patty smashed on the flat top, layered with melted American cheese, pickles, onions, and house glaze.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 145,
    badge: 'Bestseller',
    veg: false,
  },
  {
    id: 28,
    name: 'Fish Burger',
    category: 'Combo',
    price: 773,
    priceLabel: '₹773',
    currency: 'INR',
    description: 'Crispy panko-crusted white fish fillet topped with sharp tartar sauce, shredded lettuce, and melted cheese on a soft bun.',
    image: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&w=900&q=85',
    rating: 4.7,
    reviews: 62,
    veg: false,
  },
  {
    id: 29,
    name: 'Chicken Sandwich',
    category: 'Combo',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Grilled chicken fillet sandwich with maple bacon, lettuce, avocado smash, and herb mayonnaise on artisan sourdough.',
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 80,
    veg: false,
  },

  // --- MEDITERRANEAN MIX GRILL ---
  {
    id: 30,
    name: 'Combo Special (1 Person)',
    category: 'Mediterranean Mix Grill',
    price: 2149,
    priceLabel: '₹2149',
    currency: 'INR',
    description: 'Personal feast featuring 1 Chicken Tikka skewer, 1 Lamb chop, 1 Beef Kofta, saffron rice, garden salad, warm pita, and garlic dip.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 185,
    badge: 'Signature',
    veg: false,
  },
  {
    id: 31,
    name: 'Combo Special (3 Person)',
    category: 'Mediterranean Mix Grill',
    price: 5159,
    priceLabel: '₹5159',
    currency: 'INR',
    description: 'Grand family platter loaded with chicken tikka, beef kofta, lamb chops, shawarma shreds, rice bed, grilled vegetables, and dips.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 140,
    badge: 'Feast Special',
    veg: false,
  },
  {
    id: 32,
    name: 'Combo Special (5 Person)',
    category: 'Mediterranean Mix Grill',
    price: 7309,
    priceLabel: '₹7309',
    currency: 'INR',
    description: 'The ultimate royal feast platter: 5 lamb chops, 5 beef koftas, 5 chicken skewers, jumbo prawns, large Kabuli pulao, pita basket & sauces.',
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 98,
    badge: 'Royal Feast',
    veg: false,
  },

  // --- BEEF PLATTER ---
  {
    id: 33,
    name: 'Beef Kofta',
    category: 'Beef Platter',
    price: 1203,
    priceLabel: '₹1203',
    currency: 'INR',
    description: 'Three skewers of spiced minced beef kofta grilled over wood charcoal, served over saffron basmati rice with grilled tomato.',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 92,
    badge: 'Bestseller',
    veg: false,
  },
  {
    id: 34,
    name: 'Beef Chapli Kebab',
    category: 'Beef Platter',
    price: 1719,
    priceLabel: '₹1719',
    currency: 'INR',
    description: 'Authentic Pashtun style pan-fried beef chapli patties infused with pomegranate seeds, coriander, green chili, and tomatoes.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 76,
    badge: 'Chef Special',
    veg: false,
    spicy: true,
  },
  {
    id: 35,
    name: 'Beef T-Bone Steak',
    category: 'Beef Platter',
    price: 2063,
    priceLabel: '₹2063',
    currency: 'INR',
    description: 'Prime 14oz bone-in T-bone steak flame-grilled to your desired temp, finished with garlic-herb compound butter and roasted potatoes.',
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 110,
    badge: 'Luxury Cut',
    veg: false,
  },

  // --- LAMB PLATTER ---
  {
    id: 36,
    name: 'Baby Lamb Chop (3 pcs)',
    category: 'Lamb Platter',
    price: 2149,
    priceLabel: '₹2149',
    currency: 'INR',
    description: 'Tender tenderloin baby lamb chops marinated in garlic, rosemary, and olive oil, flame-grilled over open coals.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 154,
    badge: 'Signature',
    veg: false,
  },
  {
    id: 37,
    name: 'Lamb Kebab',
    category: 'Lamb Platter',
    price: 1375,
    priceLabel: '₹1375',
    currency: 'INR',
    description: 'Succulent cubes of leg of lamb marinated in onion juice and Mediterranean spices, charred to perfection.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 86,
    veg: false,
  },
  {
    id: 38,
    name: 'Lamb Shawarma Platter',
    category: 'Lamb Platter',
    price: 1075,
    priceLabel: '₹1075',
    currency: 'INR',
    description: 'Generous portion of shaved lamb shawarma meat served with fragrant rice, house salad, garlic sauce, and warm pita.',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 95,
    veg: false,
  },
  {
    id: 39,
    name: 'Lamb + Chicken Mix Platter',
    category: 'Lamb Platter',
    price: 1075,
    priceLabel: '₹1075',
    currency: 'INR',
    description: 'The best of both worlds: half spiced lamb shawarma and half garlic chicken shawarma over spiced rice.',
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 112,
    badge: 'Bestseller',
    veg: false,
  },
  {
    id: 40,
    name: 'Mix Kebab Platter',
    category: 'Lamb Platter',
    price: 1203,
    priceLabel: '₹1203',
    currency: 'INR',
    description: 'Combination platter of 1 Lamb Kebab skewer, 1 Chicken Tikka skewer, and 1 Beef Kofta skewer with sides.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 79,
    veg: false,
  },

  // --- CHICKEN PLATTER ---
  {
    id: 41,
    name: 'Chicken Tikka Kebab',
    category: 'Chicken Platter',
    price: 1117,
    priceLabel: '₹1117',
    currency: 'INR',
    description: 'Boneless chicken breast marinated in yogurt, saffron, lemon, and tandoori spice, charcoal grilled on skewers.',
    image: 'https://images.unsplash.com/photo-1727280376746-b89107a5b0df?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpY2tlbiUyMHRpa2thJTIwa2ViYWJ8ZW58MHx8MHx8fDA%3D',
    rating: 4.9,
    reviews: 165,
    badge: 'Popular',
    veg: false,
    spicy: true,
  },
  {
    id: 42,
    name: 'Chicken Behari Kebab',
    category: 'Chicken Platter',
    price: 1203,
    priceLabel: '₹1203',
    currency: 'INR',
    description: 'Melt-in-your-mouth strips of chicken marinated in raw papaya, mustard oil, fried onions, and crushed spice blend.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 94,
    badge: 'Chef Special',
    veg: false,
    spicy: true,
  },
  {
    id: 43,
    name: 'Peri Peri Chicken',
    category: 'Chicken Platter',
    price: 1375,
    priceLabel: '₹1375',
    currency: 'INR',
    description: 'Flame-grilled half chicken basted with authentic Mozambican Peri-Peri chili glaze, served with spicy rice.',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 130,
    badge: 'Must Try',
    veg: false,
    spicy: true,
  },
  {
    id: 44,
    name: 'Chicken Kofta Kebab',
    category: 'Chicken Platter',
    price: 1117,
    priceLabel: '₹1117',
    currency: 'INR',
    description: 'Minced chicken blended with fresh coriander, garlic, and paprika, hand-molded on skewers and charcoal-broiled.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 82,
    veg: false,
  },
  {
    id: 45,
    name: 'Grill Chicken',
    category: 'Chicken Platter',
    price: 1289,
    priceLabel: '₹1289',
    currency: 'INR',
    description: 'Half chicken slow-roasted over natural hardwood coals with aromatic Mediterranean herbs and lemon olive oil.',
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 104,
    veg: false,
  },
  {
    id: 46,
    name: 'Chicken Shawarma Platter',
    category: 'Chicken Platter',
    price: 1117,
    priceLabel: '₹1117',
    currency: 'INR',
    description: 'Slices of roasted chicken shawarma over seasoned rice with garlic whip, pickles, turnip, and warm pita.',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 118,
    veg: false,
  },
  {
    id: 47,
    name: 'Chicken Wings (B.B.Q)',
    category: 'Chicken Platter',
    price: 1203,
    priceLabel: '₹1203',
    currency: 'INR',
    description: 'Flame-grilled wings slathered in smoky hickory honey barbecue sauce served with house coleslaw.',
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=900&q=85',
    rating: 4.7,
    reviews: 73,
    veg: false,
  },
  {
    id: 48,
    name: 'Falafel Platter',
    category: 'Chicken Platter',
    price: 1117,
    priceLabel: '₹1117',
    currency: 'INR',
    description: 'Six golden falafel patties served over Mediterranean rice with creamy hummus, tabouli salad, tahini, and pita.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 60,
    veg: true,
  },

  // --- GRILL FISH & SEAFOOD ---
  {
    id: 49,
    name: 'Grill Salmon',
    category: 'Grill Fish & Seafood',
    price: 1891,
    priceLabel: '₹1891',
    currency: 'INR',
    description: 'Fresh wild Atlantic salmon fillet grilled to perfection, drizzled with lemon butter garlic sauce over grilled asparagus.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 172,
    badge: 'Signature',
    veg: false,
  },
  {
    id: 50,
    name: 'Tandoori Salmon',
    category: 'Grill Fish & Seafood',
    price: 1461,
    priceLabel: '₹1461',
    currency: 'INR',
    description: 'Salmon steak marinated in ajwain seeds, hung curd, and kashmiri chili, roasted in a clay tandoor oven.',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 95,
    badge: 'Chef Special',
    veg: false,
    spicy: true,
  },
  {
    id: 51,
    name: 'Grill Jumbo Shrimp (6 pcs)',
    category: 'Grill Fish & Seafood',
    price: 1289,
    priceLabel: '₹1289',
    currency: 'INR',
    description: 'Six tiger jumbo prawns skewer-grilled over wood fire, brushed with garlic herb butter and crushed black pepper.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 108,
    badge: 'Popular',
    veg: false,
  },
  {
    id: 52,
    name: 'Grill Fish Fillet',
    category: 'Grill Fish & Seafood',
    price: 1203,
    priceLabel: '₹1203',
    currency: 'INR',
    description: 'Seasoned white fish fillet grilled skin-on, served with saffron rice and lemon caper drizzle.',
    image: 'https://images.unsplash.com/photo-1535567465397-7523840f2ae9?auto=format&fit=crop&w=900&q=85',
    rating: 4.7,
    reviews: 64,
    veg: false,
  },
  {
    id: 53,
    name: 'Whole Branzino Fish',
    category: 'Grill Fish & Seafood',
    price: 2321,
    priceLabel: '₹2321',
    currency: 'INR',
    description: 'Whole Mediterranean sea bass stuffed with fresh herbs, garlic, and lemon wedges, wood-charcoal roasted.',
    image: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 88,
    badge: 'Masterpiece',
    veg: false,
  },

  // --- REFRESHER SERIES ---
  {
    id: 54,
    name: 'Strawberry Four Seasons',
    category: 'Refreshers',
    price: 601,
    priceLabel: '₹601',
    currency: 'INR',
    description: 'Chilled fruit tea layered with fresh muddled strawberries, green tea base, and basil seeds over crushed ice.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 95,
    badge: 'Refreshing',
    veg: true,
  },
  {
    id: 55,
    name: 'Passionfruit Jasmine',
    category: 'Refreshers',
    price: 601,
    priceLabel: '₹601',
    currency: 'INR',
    description: 'Fragrant jasmine green tea infused with real passionfruit pulp and fresh lime slices.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 82,
    veg: true,
  },
  {
    id: 56,
    name: 'Mango Jasmine',
    category: 'Refreshers',
    price: 601,
    priceLabel: '₹601',
    currency: 'INR',
    description: 'Tropical Alphonso mango puree shaken with brewed floral jasmine tea and ice.',
    image: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 110,
    badge: 'Popular',
    veg: true,
  },
  {
    id: 57,
    name: 'Tropical Hawaiian',
    category: 'Refreshers',
    price: 601,
    priceLabel: '₹601',
    currency: 'INR',
    description: 'Exotic blend of pineapple juice, passionfruit syrup, coconut water, and a splash of grenadine.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 67,
    veg: true,
  },
  {
    id: 58,
    name: 'Lemonade',
    category: 'Refreshers',
    price: 515,
    priceLabel: '₹515',
    currency: 'INR',
    description: 'Freshly squeezed lemon juice, organic cane sugar syrup, fresh mint leaves, and sparkling soda.',
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=900&q=85',
    rating: 4.7,
    reviews: 120,
    veg: true,
  },
  {
    id: 59,
    name: 'Ocean Blue Lemonade',
    category: 'Refreshers',
    price: 515,
    priceLabel: '₹515',
    currency: 'INR',
    description: 'Stunning blue curaçao infused citrus lemonade with mint and sparkling soda over crushed ice.',
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 140,
    badge: 'Instagram Fav',
    veg: true,
  },
  {
    id: 60,
    name: 'Peachy Paradise',
    category: 'Refreshers',
    price: 515,
    priceLabel: '₹515',
    currency: 'INR',
    description: 'Sweet white peach nectar stirred with iced black tea and fresh peach slices.',
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 54,
    veg: true,
  },
  {
    id: 61,
    name: 'Tropical Punch',
    category: 'Refreshers',
    price: 515,
    priceLabel: '₹515',
    currency: 'INR',
    description: 'Multi-layer punch with orange, guava, mango, and berry syrups topped with sparkling soda.',
    image: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=900&q=85',
    rating: 4.7,
    reviews: 48,
    veg: true,
  },
  {
    id: 62,
    name: 'Iced Tea',
    category: 'Refreshers',
    price: 515,
    priceLabel: '₹515',
    currency: 'INR',
    description: 'Classic artisanal Assam black tea brewed fresh daily, lightly sweetened with lemon wedge.',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=85',
    rating: 4.6,
    reviews: 76,
    veg: true,
  },

  // --- PROTEIN SHAKE ---
  {
    id: 63,
    name: 'French Vanilla Protein Shake',
    category: 'Shakes',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: '30g whey protein isolate blended with Madagascar vanilla bean paste, almond milk, and ice.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 84,
    badge: 'Fitness Pick',
    veg: true,
  },
  {
    id: 64,
    name: 'Peach Protein Shake',
    category: 'Shakes',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Real sliced peaches blended with vanilla protein powder, Greek yogurt, and honey.',
    image: 'https://images.unsplash.com/photo-1655505384900-60b94b56252d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1lfHx8fGVufDB8fHx8fA%3D%3D',
    rating: 4.8,
    reviews: 42,
    veg: true,
  },
  {
    id: 65,
    name: 'Milk & Yogurt Protein Shake',
    category: 'Shakes',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Thick probiotic lassi style protein shake made with fresh cultured curd, cold milk, and cardamom.',
    image: 'https://images.unsplash.com/photo-1685967836529-b0e8d6938227?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1lfHx8fGVufDB8fHx8fA%3D%3D',
    rating: 4.9,
    reviews: 66,
    veg: true,
  },
  {
    id: 66,
    name: 'Melon Protein Shake',
    category: 'Shakes',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Sweet honeydew melon blended with unflavored whey protein, coconut milk, and chia seeds.',
    image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=900&q=85',
    rating: 4.7,
    reviews: 38,
    veg: true,
  },

  // --- SMOOTHIES / SLUSH ---
  {
    id: 67,
    name: 'Mango Pomelo',
    category: 'Smoothies',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Hong Kong specialty: sweet mango smoothie layered with coconut milk, chewy sago pearls, and fresh pomelo segments.',
    image: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 156,
    badge: 'Signature',
    veg: true,
  },
  {
    id: 68,
    name: 'Peachy Slush',
    category: 'Smoothies',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Frosty slushie made with Georgia peach nectar and crushed ice topped with peach popping boba.',
    image: 'https://images.unsplash.com/photo-1579175971811-d30298ce0830?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHBlYWNoeSUyMHNsdXNofGVufDB8fDB8fHww',
    rating: 4.8,
    reviews: 62,
    veg: true,
  },
  {
    id: 69,
    name: 'Strawberry Slush',
    category: 'Smoothies',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Two-tone frozen slushie with sweet mango bottom layer and tart strawberry top layer.',
    image: 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 98,
    badge: 'Bestseller',
    veg: true,
  },
  {
    id: 70,
    name: 'Passionfruit Slush',
    category: 'Smoothies',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Tangy and sweet passionfruit crushed ice slushie garnished with fresh passionfruit seeds.',
    image: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 54,
    veg: true,
  },
  {
    id: 71,
    name: 'Mango/Strawberry Slush',
    category: 'Smoothies',
    price: 687,
    priceLabel: '₹687',
    currency: 'INR',
    description: 'Creamy blended smoothie with fresh Alphonso mango and mountain strawberries.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 70,
    veg: true,
  },

  // --- MOJITOS ---
  {
    id: 72,
    name: 'Mango Mojito',
    category: 'Mojitos',
    price: 601,
    priceLabel: '₹601',
    currency: 'INR',
    description: 'Refreshing virgin mojito with muddled fresh mint leaves, lime wedges, sweet mango puree, and fizzy soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 124,
    badge: 'Must Try',
    veg: true,
  },

  // --- WRAPS ---
  {
    id: 73,
    name: 'Bombay Frankie (Veg Wrap)',
    category: 'Wraps',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Classic Mumbai street food roll packed with spiced potato mash, paneer, mint-coriander chutney, and chaat masala.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 90,
    badge: 'Street Special',
    veg: true,
    spicy: true,
  },
  {
    id: 74,
    name: 'Paneer Wrap Plate',
    category: 'Wraps',
    price: 448,
    priceLabel: '₹448',
    currency: 'INR',
    description: 'Marinated paneer tikka grilled with peppers, wrapped in soft tortilla, served with house french fries and garlic dip.',
    image: 'https://media.istockphoto.com/id/2126797893/photo/selective-focus-of-indian-food-paneer-roll-or-paneer-kathi-roll.webp?a=1&b=1&s=612x612&w=0&k=20&c=z1YRvN1nJY7rSGoaXNBMvIByso1ALHDmujfwLpmUZ6k=',
    rating: 4.9,
    reviews: 82,
    badge: 'Popular',
    veg: true,
  },
  {
    id: 75,
    name: 'Chicken Wrap Plate',
    category: 'Wraps',
    price: 384,
    priceLabel: '₹384',
    currency: 'INR',
    description: 'Shredded roasted chicken wrap with lettuce, pickles, and garlic whip served with golden seasoned fries.',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 104,
    veg: false,
  },

  // --- SIGNATURE ---
  {
    id: 76,
    name: 'Kebab Loaded Fries (Beef / Chicken)',
    category: 'Signature',
    price: 576,
    priceLabel: '₹576',
    currency: 'INR',
    description: 'Crispy golden fries loaded with chopped beef or chicken kebab meat, melted cheese sauce, garlic mayo, and pickled jalapeños.',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 198,
    badge: 'Signature',
    veg: false,
    spicy: true,
  },
  {
    id: 77,
    name: 'Paneer Loaded Fries',
    category: 'Signature',
    price: 640,
    priceLabel: '₹640',
    currency: 'INR',
    description: 'Midway seasoned french fries topped with pan-seared paneer cubes, tikka gravy, cheese drizzle, and fresh cilantro.',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 140,
    badge: 'Chef Special',
    veg: true,
  },

  // --- BREAKFAST ---
  {
    id: 78,
    name: 'Full English',
    category: 'Breakfast',
    price: 464,
    priceLabel: '₹464',
    currency: 'INR',
    description: 'Traditional morning feast: 2 eggs your style, grilled sausages, beef bacon, baked beans, sautéed mushrooms, grilled tomato, toast & avocado.',
    image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 165,
    badge: 'Morning Classic',
    veg: false,
  },
  {
    id: 79,
    name: 'B&B Egg Wrap',
    category: 'Breakfast',
    price: 288,
    priceLabel: '₹288',
    currency: 'INR',
    description: 'Fluffy scrambled eggs, sliced avocado, cheddar cheese, and salsa wrapped in a warm buttered roti.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=85',
    rating: 4.7,
    reviews: 72,
    veg: true,
  },
  {
    id: 80,
    name: 'Spanish Omelette',
    category: 'Breakfast',
    price: 272,
    priceLabel: '₹272',
    currency: 'INR',
    description: 'Thick, fluffy egg tortilla baked with sliced potatoes, onions, bell peppers, and melted cheese, served with buttered toast.',
    image: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 64,
    veg: true,
  },
  {
    id: 81,
    name: 'Omelette',
    category: 'Breakfast',
    price: 224,
    priceLabel: '₹224',
    currency: 'INR',
    description: 'Three-egg folded omelette prepared to your liking (plain, cheese, or masala) served with buttered toast.',
    image: 'https://media.istockphoto.com/id/1910056163/photo/moringa-leaves-omelet-omelette-with-moringa-leaves-added-to-it-is-a-wholesome-omelette-recipe.webp?a=1&b=1&s=612x612&w=0&k=20&c=BIc8WaVhN3aA6XEVM9-rlu3fkr1xqhqRWExYKOKPois=',
    rating: 4.6,
    reviews: 58,
    veg: true,
  },
  {
    id: 82,
    name: 'French Toast',
    category: 'Breakfast',
    price: 352,
    priceLabel: '₹352',
    currency: 'INR',
    description: 'Thick brioche bread soaked in cinnamon vanilla custard, grilled golden, topped with fresh berries and maple syrup.',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 110,
    badge: 'Popular',
    veg: true,
  },
  {
    id: 83,
    name: 'Classic Pancakes',
    category: 'Breakfast',
    price: 384,
    priceLabel: '₹384',
    currency: 'INR',
    description: 'Stack of 3 fluffy buttermilk pancakes topped with melting whipped butter and warm maple syrup.',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 135,
    badge: 'Bestseller',
    veg: true,
  },
  {
    id: 84,
    name: 'Mocha Pancakes',
    category: 'Breakfast',
    price: 448,
    priceLabel: '₹448',
    currency: 'INR',
    description: 'Coffee-infused dark cocoa pancakes layered with whipped cream, Nutella drizzle, and chocolate curls.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 88,
    badge: 'Chef Special',
    veg: true,
  },
  {
    id: 85,
    name: 'Mini Pancakes',
    category: 'Breakfast',
    price: 352,
    priceLabel: '₹352',
    currency: 'INR',
    description: 'Bite-sized silver dollar pancakes dusted with powdered sugar, served with maple syrup and fruit jam.',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 70,
    veg: true,
  },
  {
    id: 86,
    name: 'Nutella Pancakes',
    category: 'Breakfast',
    price: 384,
    priceLabel: '₹384',
    currency: 'INR',
    description: 'Stack of fluffy pancakes smothered with warm Nutella hazelnut spread, sliced banana, and toasted hazelnuts.',
    image: 'https://images.unsplash.com/photo-1554520735-0a6b8b6ce8b7?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 145,
    badge: 'Kids & Adult Fav',
    veg: true,
  },

  // --- BREAKFAST ADD-ONS ---
  {
    id: 87,
    name: 'Sausage (2 pcs)',
    category: 'Breakfast Add-ons',
    price: 64,
    priceLabel: '₹64',
    currency: 'INR',
    description: 'Two grilled breakfast beef or chicken sausages.',
    image: 'https://images.unsplash.com/photo-1585325701165-351af916e581?auto=format&fit=crop&w=900&q=85',
    rating: 4.5,
    reviews: 30,
    veg: false,
  },
  {
    id: 88,
    name: 'Toast (2 pcs)',
    category: 'Breakfast Add-ons',
    price: 64,
    priceLabel: '₹64',
    currency: 'INR',
    description: 'Two slices of golden buttered toast.',
    image: 'https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?auto=format&fit=crop&w=900&q=85',
    rating: 4.5,
    reviews: 25,
    veg: true,
  },
  {
    id: 89,
    name: 'Egg',
    category: 'Breakfast Add-ons',
    price: 64,
    priceLabel: '₹64',
    currency: 'INR',
    description: 'One egg fried, scrambled, or poached.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=85',
    rating: 4.6,
    reviews: 35,
    veg: true,
  },
  {
    id: 90,
    name: 'Maple Syrup',
    category: 'Breakfast Add-ons',
    price: 64,
    priceLabel: '₹64',
    currency: 'INR',
    description: 'Extra cup of pure Canadian maple syrup.',
    image: 'https://images.unsplash.com/photo-1671522636384-abaa828ec275?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1hcGxlJTIwc3lydXB8ZW58MHx8MHx8fDA%3D',
    rating: 4.8,
    reviews: 40,
    veg: true,
  },
  {
    id: 91,
    name: 'Nutella',
    category: 'Breakfast Add-ons',
    price: 64,
    priceLabel: '₹64',
    currency: 'INR',
    description: 'Extra portion of creamy Nutella hazelnut spread.',
    image: 'https://media.istockphoto.com/id/478112819/photo/slice-of-bread-with-chocolate-cream.webp?a=1&b=1&s=612x612&w=0&k=20&c=xdiqHISRAw5Jltyicf_yYeyzETngdKjwEnVgn0J_blQ=',
    rating: 4.9,
    reviews: 50,
    veg: true,
  },
  {
    id: 92,
    name: 'Honey',
    category: 'Breakfast Add-ons',
    price: 64,
    priceLabel: '₹64',
    currency: 'INR',
    description: 'Natural organic wild flower honey jar.',
    image: 'https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG9uZXl8ZW58MHx8MHx8fDA%3D',
    rating: 4.7,
    reviews: 28,
    veg: true,
  },
  {
    id: 93,
    name: 'Chapati',
    category: 'Breakfast Add-ons',
    price: 64,
    priceLabel: '₹64',
    currency: 'INR',
    description: 'Freshly roasted whole wheat chapati.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=900&q=85',
    rating: 4.6,
    reviews: 32,
    veg: true,
  },
  {
    id: 94,
    name: 'Baked Beans',
    category: 'Breakfast Add-ons',
    price: 64,
    priceLabel: '₹64',
    currency: 'INR',
    description: 'Warm English style baked beans in rich tomato sauce.',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=900&q=85',
    rating: 4.5,
    reviews: 20,
    veg: true,
  },
  {
    id: 95,
    name: 'Avocado',
    category: 'Breakfast Add-ons',
    price: 64,
    priceLabel: '₹64',
    currency: 'INR',
    description: 'Freshly sliced ripe hass avocado halves.',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 45,
    veg: true,
  },

  // --- NON-VEG SNACKS ---
  {
    id: 96,
    name: 'Beef Kebabs',
    category: 'Non-Veg Snacks',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Deep-fried crispy spiced minced beef kebabs with mint coriander dip.',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 90,
    badge: 'Popular',
    veg: false,
    spicy: true,
  },
  {
    id: 97,
    name: 'Mutton Kebabs',
    category: 'Non-Veg Snacks',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Succulent fried spiced minced mutton kebabs packed with herbs and crushed black pepper.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews: 85,
    veg: false,
    spicy: true,
  },
  {
    id: 98,
    name: 'Chicken Kebabs',
    category: 'Non-Veg Snacks',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Golden fried minced chicken patties seasoned with ginger, garlic, and fresh herbs.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 78,
    veg: false,
  },
  {
    id: 99,
    name: 'Shaami Kebabs',
    category: 'Non-Veg Snacks',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Royal silky lentil and shredded mutton patties pan-fried with whole aromatic spices.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=900&q=85',
    rating: 5.0,
    reviews: 110,
    badge: 'Chef Special',
    veg: false,
  },
  {
    id: 100,
    name: 'Beef Samosas',
    category: 'Non-Veg Snacks',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Flaky golden triangular pastry stuffed with savory spiced minced beef and onions.',
    image: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 95,
    veg: false,
    spicy: true,
  },
  {
    id: 101,
    name: 'Mutton Samosas',
    category: 'Non-Veg Snacks',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Crispy fried samosas stuffed with spiced ground mutton, green peas, and mint.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 82,
    veg: false,
  },
  {
    id: 102,
    name: 'Chicken Samosas',
    category: 'Non-Veg Snacks',
    price: 288,
    priceLabel: '₹288',
    currency: 'INR',
    description: 'Golden crunchy samosa pockets filled with tender spiced minced chicken breast.',
    image: 'https://plus.unsplash.com/premium_photo-1695297516142-398762d80f66?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGNoaWNrZW4lMjBzYW1vc2F8ZW58MHx8MHx8fDA%3D',
    rating: 4.8,
    reviews: 102,
    badge: 'Bestseller',
    veg: false,
  },
  {
    id: 103,
    name: 'Chicken Wrap',
    category: 'Non-Veg Snacks',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Soft flatbread roll stuffed with pulled grilled chicken, garlic sauce, and fresh pickles.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=85',
    rating: 4.7,
    reviews: 64,
    veg: false,
  },

  // --- VEG SNACKS ---
  {
    id: 104,
    name: 'Samosas',
    category: 'Veg Snacks',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Crispy pastry triangles stuffed with spiced potatoes, green peas, cumin, and mint chutney.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85',
    rating: 4.9,
    reviews: 140,
    badge: 'All Time Fav',
    veg: true,
  },
  {
    id: 105,
    name: 'B&B Fries',
    category: 'Veg Snacks',
    price: 224,
    priceLabel: '₹224',
    currency: 'INR',
    description: 'Signature Midway house-seasoned fries tossed with secret spice rub and served with garlic mayo.',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 115,
    veg: true,
  },
  {
    id: 106,
    name: 'Maru Bhajia',
    category: 'Veg Snacks',
    price: 192,
    priceLabel: '₹192',
    currency: 'INR',
    description: 'Authentic East African style thin potato slices dipped in spiced chickpea batter and deep-fried crisp.',
    image: 'https://images.unsplash.com/photo-1613764816537-a43baeb559c1?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWFydSUyMGJoYWppYXxlbnwwfHwwfHx8MA%3D%3D',
    rating: 4.9,
    reviews: 94,
    badge: 'Cultural Fav',
    veg: true,
    spicy: true,
  },
  {
    id: 107,
    name: 'Dal Bhajia',
    category: 'Veg Snacks',
    price: 192,
    priceLabel: '₹192',
    currency: 'INR',
    description: 'Golden crunchy lentil fritters seasoned with green chili, ginger, and curry leaves.',
    image: 'https://media.istockphoto.com/id/1731327372/photo/pakora-or-pakoda-a-traditional-and-popular-indian-vegetarian-snack-in-a-tray.webp?a=1&b=1&s=612x612&w=0&k=20&c=jtkx3WWQXYva4sfF4cvlNcgkx8ibvjBkYfMua2ZPnUU=',
    rating: 4.7,
    reviews: 58,
    veg: true,
  },
  {
    id: 108,
    name: 'Spring Potato',
    category: 'Veg Snacks',
    price: 192,
    priceLabel: '₹192',
    currency: 'INR',
    description: 'Whole spiral-cut potato skewered, deep-fried crunchy, and dusted with tangy peri peri seasoning.',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=900&q=85',
    rating: 4.8,
    reviews: 86,
    badge: 'Kids Fav',
    veg: true,
    spicy: true,
  },
  {
    id: 109,
    name: 'Dal Kachori',
    category: 'Veg Snacks',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Crispy flaky fried puff pastry stuffed with spicy yellow moong dal and served with sweet tamarind chutney.',
    image: 'https://media.istockphoto.com/id/653841382/photo/indian-vegetarian-food-kachori.webp?a=1&b=1&s=612x612&w=0&k=20&c=Cwi4wBziEwU1WHUfY5cWZPr5jo1gbD3yq9oK7Cf7pWA=',
    rating: 4.8,
    reviews: 62,
    veg: true,
  },
  {
    id: 110,
    name: 'Spring Roll',
    category: 'Veg Snacks',
    price: 256,
    priceLabel: '₹256',
    currency: 'INR',
    description: 'Golden fried crispy spring rolls packed with shredded cabbage, carrots, bell peppers, and sweet chili sauce.',
    image: 'https://images.unsplash.com/photo-1669340781012-ae89fbac9fc3?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c3ByaW5nJTIwcm9sbHxlbnwwfHwwfHx8MA%3D%3D',
    rating: 4.7,
    reviews: 70,
    veg: true,
  },
  {
    id: 111,
    name: 'Plain Fries',
    category: 'Veg Snacks',
    price: 128,
    priceLabel: '₹128',
    currency: 'INR',
    description: 'Classic crispy salted golden french fries with tomato ketchup.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&w=900&q=85',
    rating: 4.6,
    reviews: 50,
    veg: true,
  },
]
